name: Run the Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Make entrypoint script executable
      run: chmod +x .entrypoint.sh

    - name: Unit Testing
      run: |
        cd ciphers_project
        python manage.py test

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: jayasandeepketha
        password: ${{ secrets.ACCESS_TOKEN }}

    - name: Build and Push the Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/jayasandeepketha/ciphers-service:latest
        file: ./Dockerfile
        context: .
